### ISSUE TITLE
Enum values should be lowercase

### ISSUE THREAD

**Issue by emorris00** [KyleJonesWinsted/suitecloud-unit-testing-stubs#3]
Currently they are uppercase. This will incorrectly fail code that is comparing against text instead of the enum. See official netsuite stubs.
https://github.com/oracle/netsuite-suitecloud-sdk/blob/master/packages/unit-testing/stubs/record/record.js

Example:
record.Type.SALES_ORDER should be "salesorder" not "SALESORDER".

EDIT: looking into it further it looks like some enums should have uppercase values and some should have lowercase.

**Comment by KyleJonesWinsted** [comment]
Thanks for catching this! I went through all of the enums in the NetSuite Script Debugger and fixed any that were in the wrong casing. Let me know if you find any that I may have missed.

**Comment by emorris00** [comment]
What version of Netsuite are you on? I am getting some different values for some of the enums.

**Comment by KyleJonesWinsted** [comment]
I tested in a Development account on 2022.2. Which values are you seeing that are different?

**Comment by emorris00** [comment]
Sandbox account on 2022.1. Submitted a pull request so you can see the differences.
https://github.com/KyleJonesWinsted/suitecloud-unit-testing-stubs/pull/5

**Comment by KyleJonesWinsted** [comment]
Closed by #5
